name: smart_safe_nav
description: "Smart Safe Route Navigation App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 🔥 Firebase (latest compatible)
  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.0

  # 🗺 Maps
  flutter_map: ^6.2.1
  latlong2: ^0.9.1

  # 📍 Location
  geolocator: ^12.0.0
  geocoding: ^3.0.0
#  location: ^6.0.2

  # 🔐 Permissions
  permission_handler: ^11.3.1

  # 💾 Storage
  shared_preferences: ^2.3.0

  # 🌐 Network
  http: ^1.2.0
  url_launcher: ^6.3.1

  # 🎨 UI
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1

  # 🔊 TTS
  flutter_tts: ^4.0.2

  # 📄 Utils
  intl: ^0.19.0
  file_picker: ^8.1.2
  webview_flutter: ^4.7.0
  syncfusion_flutter_pdf: ^25.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
#  assets:
#    - assets/